imports:
  - "base.yaml"

device:
  type: torch.device
  type_str: "cuda"
  index: 0

transform:
  type: mlprogram.functools.Sequence
  funcs:
    type: collections.OrderedDict
    items:
      - - "extract_reference"
        - type: mlprogram.utils.transform.text.ExtractReference
          extract_reference: "@/extract_reference"
      - - "encode_word"
        - type: mlprogram.utils.transform.text.EncodeWordQuery
          word_encoder: "@/encoder.word_encoder"
      - - "encode_char"
        - type: mlprogram.utils.transform.text.EncodeCharacterQuery
          char_encoder: "@/encoder.char_encoder"
          max_word_length: "@/params.max_word_length"
      - - "transform_code"
        - type: mlprogram.utils.transform.action_sequence.GroundTruthToActionSequence
          parser: "@/parser"
      - - "add_previous_action"
        - type: mlprogram.utils.transform.action_sequence.AddPreviousActions
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
      - - "add_previous_action_rule"
        - type: mlprogram.utils.transform.action_sequence.AddPreviousActionRules
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
          max_arity: "@/params.max_arity"
      - - "add_action_sequence_as_tree"
        - type: mlprogram.utils.transform.action_sequence.AddActionSequenceAsTree
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
      - - "add_query"
        - type: mlprogram.utils.transform.action_sequence.AddQueryForTreeGenDecoder
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
          max_depth: "@/params.max_tree_depth"
      - - "transform_ground_truth"
        - type: mlprogram.utils.transform.action_sequence.EncodeActionSequence
          action_sequence_encoder: "@/encoder.action_sequence_encoder"

optimizer:
  type: torch.optim.Optimizer
  optimizer_cls:
    type: fairseq.optim.Adafactor
  model: "@/model"

main:
  type: mlprogram.entrypoint.train_supervised
  workspace_dir: "output/workspace"
  output_dir: "@/output_dir"
  dataset: "@/train_dataset"
  model: "@/model"
  optimizer: "@/optimizer"
  loss:
    type: torch.nn.Sequential
    modules:
      type: collections.OrderedDict
      items:
        - - "loss"
          - type: mlprogram.nn.action_sequence.Loss
        - - "pick"
          - type: mlprogram.nn.Function
            f:
              type: Pick
              key: "output@action_sequence_loss"
  evaluate:
    type: mlprogram.entrypoint.EvaluateSynthesizer
    dataset: "@/test_dataset"
    synthesizer: "@/synthesizer"
    metrics: "@/metrics"
    top_n: "@/params.metric_top_n"
    n_process: "@/params.n_evaluate_process"
  metric: "bleu@1"
  threshold: "@/params.metric_threshold"
  maximize: True
  collate:
    type: mlprogram.functools.Compose
    funcs:
      type: collections.OrderedDict
      items:
        - - "transform"
          - type: mlprogram.functools.Map
            func: "@/transform"
        - - "collate"
          - "@/collate.collate"
  batch_size: "@/params.batch_size"
  length:
    type: mlprogram.entrypoint.train.Epoch
    n: "@/params.n_epoch"
  evaluation_interval:
    type: mlprogram.entrypoint.train.Epoch
    n: "@/params.eval_interval"
  snapshot_interval:
    type: mlprogram.entrypoint.train.Epoch
    n: "@/params.snapshot_interval"
  device: "@/device"
