output_dir: "output/output"
device:
  type: torch.device
  type_str: "cuda"
  index: 0

dataset:
  type: mlprogram.datasets.hearthstone.download
test_dataset: "@/dataset.test"
valid_dataset: "@/dataset.valid"

options:
  type: mlprogram.actions.ActionOptions
  retain_variadic_fields: true
  split_non_terminal: true

to_action_sequence:
  type: mlprogram.utils.Compose
  funcs:
    type: collections.OrderedDict
    items:
      - - "parse"
        - type: mlprogram.languages.python.Parse
      - - "ast_to_action_sequence"
        - type: mlprogram.utils.transform.AstToSingleActionSequence
          tokenize:
            type: mlprogram.languages.python.TokenizeToken
          options: "@/options"

encoder:
  word_encoder:
    type: mlprogram.utils.load
    file:
      type: os.path.join
      args:
        - "@/output_dir"
        - "word_encoder.pt"
  char_encoder:
    type: mlprogram.utils.load
    file:
      type: os.path.join
      args:
        - "@/output_dir"
        - "char_encoder.pt"
  action_sequence_encoder:
    type: mlprogram.utils.load
    file:
      type: os.path.join
      args:
        - "@/output_dir"
        - "action_sequence_encoder.pt"

transform:
  transform_input:
    type: mlprogram.utils.transform.treegen.TransformQuery
    extract_query:
      type: mlprogram.datasets.hearthstone.TokenizeQuery
    word_encoder: "@/encoder.word_encoder"
    char_encoder: "@/encoder.char_encoder"
    max_word_length: 128
  transform_action_sequence:
    type: mlprogram.utils.transform.treegen.TransformActionSequence
    action_sequence_encoder: "@/encoder.action_sequence_encoder"
    max_arity: 128
    max_depth: 128
    train: false

action_sequence_reader:
  type: mlprogram.nn.nl2code.ActionSequenceReader
  num_rules: "@/encoder.action_sequence_encoder._rule_encoder.vocab_size"
  num_tokens: "@/encoder.action_sequence_encoder._token_encoder.vocab_size"
  num_node_types: "@/encoder.action_sequence_encoder._node_type_encoder.vocab_size"
  node_type_embedding_size: 64
  embedding_size: 128

model:
  type: torch.nn.Sequential
  modules:
    type: collections.OrderedDict
    items:
      - - "encoder"
        - type: mlprogram.nn.treegen.NLReader
          token_num: "@/encoder.word_encoder.vocab_size"
          char_num: "@/encoder.char_encoder.vocab_size"
          max_token_len: 128
          char_embed_size: 256
          hidden_size: 256
          n_heads: 1
          dropout: 0.15
          n_blocks: 6
      - - "decoder"
        - type: torch.nn.Sequential
          modules:
            type: collections.OrderedDict
            items:
              - - "action_sequence_reader"
                - type: mlprogram.nn.treegen.ActionSequenceReader
                  rule_num: "@/encoder.action_sequence_encoder._rule_encoder.vocab_size"
                  token_num: "@/encoder.action_sequence_encoder._token_encoder.vocab_size"
                  node_type_num: "@/encoder.action_sequence_encoder._node_type_encoder.vocab_size"
                  max_arity: 128
                  rule_embed_size: 256
                  hidden_size: 256
                  tree_conv_kernel_size: 3
                  n_heads: 1
                  dropout: 0.15
                  n_blocks: 6
              - - "decoder"
                - type: mlprogram.nn.treegen.Decoder
                  rule_num: "@/encoder.action_sequence_encoder._rule_encoder.vocab_size"
                  max_depth: 128
                  feature_size: 256
                  hidden_size: 1024
                  out_size: 256
                  n_heads: 1
                  dropout: 0.15
                  n_blocks: 6
              - - "predictor"
                - type: mlprogram.nn.treegen.Predictor
                  feature_size: 256
                  nl_feature_size: 256
                  rule_size: "@/encoder.action_sequence_encoder._rule_encoder.vocab_size"
                  token_size: "@/encoder.action_sequence_encoder._token_encoder.vocab_size"  # TODO
                  hidden_size: 256

collate:
  type: mlprogram.utils.data.Collate
  device: "@/device"
  word_nl_query:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  char_nl_query:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  nl_query_features:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  previous_actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  previous_action_rules:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  depthes:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: false
    dim: 1
    padding_value: 0
  adjacency_matrix:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: false
    dim: 0
    padding_value: 0
  action_queries:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  ground_truth_actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1

synthesizer:
  type: mlprogram.synthesizers.BeamSearch
  beam_size: 15
  max_step_size: 350
  sampler:
    type: mlprogram.samplers.ActionSequenceSampler
    encoder: "@/encoder.action_sequence_encoder"
    get_token_type: null
    is_subtype:
      type: mlprogram.languages.python.IsSubtype
    transform_input: "@/transform.transform_input"
    transform_action_sequence: "@/transform.transform_action_sequence"
    collate: "@/collate"
    module: "@/model"
    options: "@/options"

# Metrics
metrics:
  accuracy:
    type: mlprogram.metrics.Accuracy
    parse:
      type: mlprogram.languages.python.Parse
    unparse:
      type: mlprogram.languages.python.Unparse
  bleu:
    type: mlprogram.metrics.Bleu
    parse:
      type: mlprogram.languages.python.Parse
    unparse:
      type: mlprogram.languages.python.Unparse

main:
  type: mlprogram.entrypoint.nl2prog.evaluate
  workspace_dir: "output/workspace"
  input_dir: "@/output_dir"
  output_dir: "@/output_dir"
  test_dataset: "@/test_dataset"
  valid_dataset: "@/valid_dataset"
  synthesizer: "@/synthesizer"
  metrics: "@/metrics"
  main_metric:
    - 1
    - "bleu"
  top_n:
    - 1
  device: "@/device"
