imports:
  - "nl2code_base.yaml"

device:
  type: torch.device
  type_str: "cpu"
  index: 0

output_dir: "output/output"

dataset:
  type: mlprogram.datasets.nl2bash.download

encoder:
  word_encoder:
    type: mlprogram.utils.load
    file:
      type: os.path.join
      args:
        - "@/output_dir"
        - "word_encoder.pt"
  action_sequence_encoder:
    type: mlprogram.utils.load
    file:
      type: os.path.join
      args:
        - "@/output_dir"
        - "action_sequence_encoder.pt"

main:
  type: mlprogram.entrypoint.evaluate
  workspace_dir: "output/workspace"
  input_dir: "@/output_dir"
  output_dir: "@/output_dir"
  valid_dataset: "@/valid_dataset"
  model: "@/model"
  synthesizer: "@/synthesizer"
  metrics: "@/metrics"
  top_n:
    - 1
    - 3
  device: "@/device"
  n_process: 2
