normalize_dataset:
  type: mlprogram.utils.transform.NormalizeGroundTruth
  normalize:
    type: mlprogram.functools.Sequence
    funcs:
      type: collections.OrderedDict
      items:
        - - parse
          - "@/parser.parse"
        - - unparse
          - "@/parser.unparse"

train_dataset: "@/dataset.train"
test_dataset:
  type: mlprogram.utils.data.transform
  dataset: "@/dataset.test"
  transform: "@/normalize_dataset"
valid_dataset:
  type: mlprogram.utils.data.transform
  dataset: "@/dataset.valid"
  transform: "@/normalize_dataset"

encoder:
  word_encoder:
    type: with_file_cache
    path:
      type: os.path.join
      args:
        - "@/output_dir"
        - "word_encoder.pt"
    config:
      type: torchnlp.encoders.LabelEncoder
      sample:
        type: mlprogram.utils.data.get_words
        dataset: "@/train_dataset"
        extract_reference: "@/extract_reference"
      min_occurrences: "@/params.word_threshold"
  action_sequence_encoder:
    type: with_file_cache
    path:
      type: os.path.join
      args:
        - "@/output_dir"
        - "action_sequence_encoder.pt"
    config:
      type: mlprogram.encoders.ActionSequenceEncoder
      samples:
        type: mlprogram.utils.data.get_samples
        dataset: "@/train_dataset"
        parser: "@/parser"
      token_threshold: "@/params.token_threshold"

action_sequence_reader:
  type: mlprogram.nn.nl2code.ActionSequenceReader
  num_rules: "@/encoder.action_sequence_encoder._rule_encoder.vocab_size"
  num_tokens: "@/encoder.action_sequence_encoder._token_encoder.vocab_size"
  num_node_types: "@/encoder.action_sequence_encoder._node_type_encoder.vocab_size"
  node_type_embedding_size: "@/params.node_type_embedding_size"
  embedding_size: "@/params.embedding_size"
model:
  type: torch.share_memory_
  model:
    type: torch.nn.Sequential
    modules:
      type: collections.OrderedDict
      items:
        - - "encoder"
          - type: mlprogram.nn.nl2code.NLReader
            num_words: "@/encoder.word_encoder.vocab_size"
            embedding_dim: "@/params.embedding_size"
            hidden_size: "@/params.hidden_size"
            dropout: "@/params.dropout"
        - - "decoder"
          - type: torch.nn.Sequential
            modules:
              type: collections.OrderedDict
              items:
                - - "action_sequence_reader"
                  - "@/action_sequence_reader"
                - - "decoder"
                  - type: mlprogram.nn.nl2code.Decoder
                    query_size: "@/params.hidden_size"
                    input_size:
                      type: add
                      x:
                        type: mul
                        x: 2
                        y: "@/params.embedding_size"
                      y: "@/params.node_type_embedding_size"
                    hidden_size: "@/params.hidden_size"
                    att_hidden_size: "@/params.attr_hidden_size"
                    dropout: "@/params.dropout"
                - - "predictor"
                  - type: mlprogram.nn.nl2code.Predictor
                    reader: "@/action_sequence_reader"
                    embedding_size: "@/params.embedding_size"
                    query_size: "@/params.hidden_size"
                    hidden_size: "@/params.hidden_size"
                    att_hidden_size: "@/params.attr_hidden_size"

collate:
  type: mlprogram.utils.data.Collate
  device: "@/device"
  word_nl_query:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  nl_query_features:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  reference_features:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  previous_actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  previous_action_rules:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1
  history:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: false
    dim: 1
    padding_value: 0
  hidden_state:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: false
    dim: 0
    padding_value: 0
  state:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: false
    dim: 0
    padding_value: 0
  ground_truth_actions:
    type: mlprogram.utils.data.CollateOptions
    use_pad_sequence: true
    dim: 0
    padding_value: -1

transform_input:
  type: mlprogram.functools.Compose
  funcs:
    type: collections.OrderedDict
    items:
      - - "extract_reference"
        - type: mlprogram.utils.transform.text.ExtractReference
          extract_reference: "@/extract_reference"
      - - "encode_word_query"
        - type: mlprogram.utils.transform.text.EncodeWordQuery
          word_encoder: "@/encoder.word_encoder"
transform_action_sequence:
  type: mlprogram.functools.Compose
  funcs:
    type: collections.OrderedDict
    items:
      - - "add_previous_action"
        - type: mlprogram.utils.transform.action_sequence.AddPreviousActions
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
      - - "add_action"
        - type: mlprogram.utils.transform.action_sequence.AddActions
          action_sequence_encoder: "@/encoder.action_sequence_encoder"
      - - "add_state"
        - type: mlprogram.utils.transform.action_sequence.AddStateForRnnDecoder
      - - "add_history"
        - type: mlprogram.utils.transform.action_sequence.AddHistoryState

synthesizer:
  type: mlprogram.synthesizers.BeamSearch
  beam_size: "@/params.beam_size"
  max_step_size: "@/params.max_step_size"
  sampler:
    type: mlprogram.samplers.transform
    sampler:
      type: mlprogram.samplers.ActionSequenceSampler
      encoder: "@/encoder.action_sequence_encoder"
      is_subtype: "@/is_subtype"
      transform_input: "@/transform_input"
      transform_action_sequence: "@/transform_action_sequence"
      collate: "@/collate"
      module: "@/model"
    transform: "@/parser.unparse"
